# Site
repository: simjjy/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

encoding: UTF-8

# Content configuration version
version: 2

# Personal info
name: 심 재 진
title: 솔루션 개발자
email: simjjy89@gmail.com
# email_title: Email (Email title override)
phone: 010-4232-3226
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)
website: https://github.com/simjjy89

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
#github_username:  jekyll
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Link name
 # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
 # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: 자기소개(Use this to override about section title)
about_profile_image: /images/simjaejin.jpg 
about_content: | # this will include new lines to allow paragraphs
  검색/빅데이터 솔루션 회사에 다니고 있는 6년차 개발자 입니다. 주로 공공기관 및 공기업 프로젝트를 수행하고 있습니다. 다양한 프로젝트를 경험하며, 새로운 환경에 적응하는것에 거부감이 없고 다양한 사람들과 능동적으로 소통을 하며 협업을 하였습니다.

  Spring 프레임 워크 등, Back-End 에 솔루션 연동 API 구축을 주로 하였고, API에서 가져온 데이터의 Front-End 처리도 같이 하고있습니다. 
  
content: 
  - title: 보유기술
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>Programming Language</mark>  Java, Javascript, HTML

      <mark>Framework</mark>  Spring Framework

      <mark>Library</mark>  jQuery

      <mark>Server</mark>  Apache, jetty

      <mark>DataBase</mark>  Oracle, tibero, mySql

      <mark>OS</mark>  Windows, Linux

      <mark>Tool</mark>  Eclipse, SVN, github, vi

  - title: 경력 
    layout: list
    content:
      - layout: left
        title: 와이즈넛
        sub_title: 
        caption: 기간 (2016.04 ~ 현재)
        link: http://www.wisenut.co.kr
        quote: > 
        description: | 
          공공개발팀 (2016.10 ~ ) <br>
          - 자사 솔루션 구축 및 커스터마이징 <br><br><br> 

          기술지원팀 (2016.04 ~ 2016.09) <br>
          - 프로젝트 유지보수  
          - 단기 프로젝트 수행 <br><br>

  - title: 프로젝트 # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      <font size=4><strong>군사정보통합처리체계 MIMS 성능개량 체계개발 사업</strong> (2021.04 ~ )</font> 
      육∙해∙공 C4I 체계 및 각종 센서와의 연동을 통해 군사정보를 종합 관리하는 MIMS 시스템에 대한 성능 개량 사업 <br>
      <mark>주요 업무</mark>
      - 통합검색 및 빅데이터 솔루션 연동 API 설계 및 구축 (전자정부 프레임워크 Spring)
      - Websquare를 사용하여 통합검색 및 빅데이터 연동 화면 작업  

      <mark>개선 및 문제해결 사례</mark>
      - qq
      - Websquare를 사용하여 통합검색 및 빅데이터 연동 화면 작업 <br><br><br>

      <font size=4><strong>통계청 마이크로데이터 거버넌스 구축 데이터 멘토링 시스템 확대 사업</strong> (2020.06 ~ 2021.03)</font> 
      통계청 마이크로데이터 통합서비스 고도화 사업 <br>
      <mark>주요 업무</mark>
      - MDIS 사이트 통합검색 및 챗봇 구축
      - 통합검색 페이지 디자인 및 기능 수정 

      <mark>개선 및 문제해결 사례</mark>
      - AS-IS 챗봇은 시나리오별 답변을 Front End에서 처리되는 부분이 많았습니다. script영역의 코드의 가독성이 떨어지는 문제가 있었고 새로운 요구사항과 기능을 추가하기에 앞서 유지보수가 어려울것이라 판단하여, script 영역의 코드를 간소화 하고 Back-End에서 시나리오에 따라 답변을 처리하도록 리팩토링하였습니다.
      - 프로젝트 초기부터 업무협의를 함께 하던 클라이언트가 다른 지역으로 발령이 가게되어 새로운 인원으로 대체되었는데 기존 요구사항과 상이한 요청사항을 하였습니다. 프로젝트 막바지였기에 요청사항을 수용할 수 없었기 때문에 기존 작업방향의 당위성을 잘 설명하여 이해를 시켰고 추후에 나오는 요청사항은 잘 정리하여 다음 고도화 사업때 적용하도록 하여 마무리 지었습니다. <br><br><br>

      <font size=4><strong>행정안전부 행정서비스 통합제공 시스템 구축(2단계 3차)</strong> (2019.12 ~ 2020.05)</font> 
      정부24 사이트 통합 제공 시스템 고도화 사업 <br>
      <mark>주요 업무</mark>
      - MDIS 사이트 통합검색 및 챗봇 구축
      - 통합검색 페이지 디자인 및 기능 수정 

      <mark>개선 및 문제해결 사례</mark>
      - ss
      - ss <br><br><br>

      <font size=4><strong>한국수출입은행 디지털워크플레이스 구축</strong> (2019.07 ~ 2019.11)</font> 
      정부24 사이트 통합 제공 시스템 고도화 사업 <br>
      <mark>주요 업무</mark>
      - MDIS 사이트 통합검색 및 챗봇 구축
      - 통합검색 페이지 디자인 및 기능 수정 

      <mark>개선 및 문제해결 사례</mark>
      - ss
      - ss <br><br><br>

      <font size=2><strong>청와대 기록관리시스템 구축 사업-분리발주(검색엔진) </strong> (2019.011 ~ 2019.12)</font><br>
      <font size=2><strong>건강보험심사평가원 2018년도 대내외 업무서비스 개선(루트온플러스) </strong> (2019.011 ~ 2019.12)</font><br>
      <font size=2><strong>식품의약품안전처 2018년도 차세대 의약품통합정보시스템 구축 개발 </strong> (2019.011 ~ 2019.12)</font> <br>
      <font size=2><strong>식품의약품안전처 대표홈페이지 클라우드이전SW  </strong> (2019.011 ~ 2019.12)</font> <br>
      <font size=2><strong>건강보험심사평가원 대내외 업무 서비스 개선사업 </strong> (2019.011 ~ 2019.12)</font> <br> 
      <font size=2><strong>강원도 동계평창올림픽 포털 구축 사업 </strong> (2018.01 ~ 2018.02)</font> <br>
      <font size=2><strong>방송통신심의위원회 통합 홈페이지 전면 개편 사업 </strong> (2017.11 ~ 2017.12)</font> <br>
      <font size=2><strong>건강보험심사평가원 대내외 업무 서비스 개선사업 </strong> (2017.07 ~ 2018.02)</font> <br>
      <font size=2><strong>한국해양과학기술진흥원 해양수산 R&D 지식정보시스템(OFRIS) 구축 (2차년도) SW 구매 </strong> (2017.05 ~ 2017.07)</font> <br>
      <font size=2><strong>공무원연금공단 서브홈페이지 통합 및 기능개선 </strong> (2017.03 ~ 2017.04)</font> <br>
      <font size=2><strong>아시아문화원 아시아 문화 디지털 콘텐츠 구축을 위한 연구 및 수집 용역 </strong> (2016.11 ~ 2017.03)</font> <br>
      <font size=2><strong>국방기술품질원 국방기술정보통합서비스(DITIS)노후장비(인터넷망)교체사업_분리발주(검색SW) </strong> (2016.10 ~ 2016.11)</font> <br>

      

  - title: 학력 사항
    layout: list
    content:
      - layout: left
        title: 대학교
        sub_title:  
        caption: 기간 (2009.04 - 2016.02)
        quote: > 
        description: | # this will include new lines to allow paragraphsz
          - 수원대학교 정보통신공학과(학사)
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
